### PR TITLE
Updated to OT 1.16

### PR DESCRIPTION
**Pull request by regislebrun**
Also updated the embedded version of fftw and the associated compilation flags. This module is **really** useful if one needs performance in FFT computations. The following benchmark shows the poor performance of numpy (1.19.4) wrt OT/KissFFT and otfftw/FFTW:
```
import numpy as np
import openturns as ot
import otfftw
from time import time

for size in [10, 100, 1000, 10000, 100000, 1000000, 10000000, 100000000]:
    dataX = ot.RandomGenerator.Generate(size)
    dataY = ot.RandomGenerator.Generate(size)
    data = ot.ComplexCollection([x+1j*y for (x,y) in zip(dataX, dataY)])
    t0 = time()
    res = np.fft.fft(data)
    t1 = time()
    t_numpy = t1 - t0
    t0 = time()
    res = ot.FFT().transform(data)
    t1 = time()
    t_ot = t1 - t0
    t0 = time()
    res = otfftw.FFTW().transform(data)
    t1 = time()
    t_otfftw = t1 - t0
    print("size=", str(size).rjust(9), "[numpy %.2e, numpy/ot %.2g, numpy/otfftw %.2g, ot/otfftw %.2g]" % (t_numpy, t_numpy/t_ot, t_numpy/t_otfftw, t_ot/t_otfftw))

for nsize in range(10):
    size = 8**nsize
    dataX = ot.RandomGenerator.Generate(size)
    dataY = ot.RandomGenerator.Generate(size)
    data = ot.ComplexCollection([x+1j*y for (x,y) in zip(dataX, dataY)])
    t0 = time()
    res = np.fft.fft(data)
    t1 = time()
    t_numpy = t1 - t0
    t0 = time()
    res = ot.FFT().transform(data)
    t1 = time()
    t_ot = t1 - t0
    t0 = time()
    res = otfftw.FFTW().transform(data)
    t1 = time()
    t_otfftw = t1 - t0
    print("size=", str(size).rjust(9), "[numpy %.2e, numpy/ot %.2g, numpy/otfftw %.2g, ot/otfftw %.2g]" % (t_numpy, t_numpy/t_ot, t_numpy/t_otfftw, t_ot/t_otfftw))
```
The output is:
```
size=        10 [numpy 2.21e-03, numpy/ot 3.4, numpy/otfftw 1.1, ot/otfftw 0.33]
size=       100 [numpy 4.46e-04, numpy/ot 8.2, numpy/otfftw 2.3, ot/otfftw 0.28]
size=      1000 [numpy 2.98e-03, numpy/ot 16, numpy/otfftw 7, ot/otfftw 0.44]
size=     10000 [numpy 1.04e-02, numpy/ot 18, numpy/otfftw 37, ot/otfftw 2]
size=    100000 [numpy 5.79e-02, numpy/ot 11, numpy/otfftw 33, ot/otfftw 2.9]
size=   1000000 [numpy 6.13e-01, numpy/ot 6.7, numpy/otfftw 21, ot/otfftw 3.1]
size=  10000000 [numpy 6.35e+00, numpy/ot 4.5, numpy/otfftw 19, ot/otfftw 4.2]
size= 100000000 [numpy 6.24e+01, numpy/ot 3.3, numpy/otfftw 14, ot/otfftw 4.2]
size=         1 [numpy 3.81e-02, numpy/ot 1.4e+03, numpy/otfftw 5.6e+02, ot/otfftw 0.41]
size=         8 [numpy 1.11e-04, numpy/ot 13, numpy/otfftw 5, ot/otfftw 0.39]
size=        64 [numpy 5.96e-05, numpy/ot 7.1, numpy/otfftw 2.6, ot/otfftw 0.36]
size=       512 [numpy 2.99e-04, numpy/ot 13, numpy/otfftw 8.5, ot/otfftw 0.67]
size=      4096 [numpy 2.37e-03, numpy/ot 17, numpy/otfftw 34, ot/otfftw 2]
size=     32768 [numpy 1.90e-02, numpy/ot 14, numpy/otfftw 38, ot/otfftw 2.7]
size=    262144 [numpy 1.52e-01, numpy/ot 12, numpy/otfftw 32, ot/otfftw 2.7]
size=   2097152 [numpy 1.30e+00, numpy/ot 5.6, numpy/otfftw 17, ot/otfftw 3]
size=  16777216 [numpy 1.05e+01, numpy/ot 4.4, numpy/otfftw 10, ot/otfftw 2.4]
size= 134217728 [numpy 8.42e+01, numpy/ot 3.1, numpy/otfftw 7.9, ot/otfftw 2.5]
```
We see that numpy has poor performances compared to KissFFT and FFTW, and FFTW gives a significant additional speedup for large cases. Unfortunately we cannot simply use FFTW within OT due to license issues.
Several other points have to be addressed:
* The CMake infrastructure of the module has to be updated as it generates several warnings
* The embedded fftw library is compiled using autotools instead of CMake
* I was not able to link the module against a parallel version of fftw (either omp or pthreads) but it should provide an additional speed-up
* The documentation is still in plain LaTeX and not in rst/sphinx format.

### CODE REVIEW

**Comment by jschueller** [comment]
a rebase is needed, seems you started from a quite out of sync master

**Comment by regislebrun** [comment]
@jschueller I may have missed something. I forked openturns/otfftw, then I tried to compile it against the current master of OT and got a lot of errors. I updated the code in otfftw and now I see that I was working on an old version of the module, as you already did the same work some times ago. You also removed the embedded version of fftw, so there is no more need for my update!

**Comment by jschueller** [comment]
the benchmark is still useful
I noticed they switched to pocketfft (https://gitlab.mpcdf.mpg.de/mtr/pocketfft) in scipy when fftw cannot be used,
maybe this is a better replacement for kissfft.

**Comment by regislebrun** [comment]
I checked the scipy.fft performance with the same benchmark (and using the pthread version of my system libfftw):
```
import scipy.fft
import openturns as ot
import otfftw
from time import time

for size in [10, 100, 1000, 10000, 100000, 1000000, 10000000, 100000000]:
    dataX = ot.RandomGenerator.Generate(size)
    dataY = ot.RandomGenerator.Generate(size)
    data = ot.ComplexCollection([x+1j*y for (x,y) in zip(dataX, dataY)])
    t0 = time()
    res = scipy.fft.fft(data)
    t1 = time()
    t_scipy = t1 - t0
    t0 = time()
    res = ot.FFT().transform(data)
    t1 = time()
    t_ot = t1 - t0
    t0 = time()
    res = otfftw.FFTW().transform(data)
    t1 = time()
    t_otfftw = t1 - t0
    print("size=", str(size).rjust(9), "[scipy %.2e, scipy/ot %.2g, scipy/otfftw %.2g, ot/otfftw %.2g]" % (t_scipy, t_scipy/t_ot, t_scipy/t_otfftw, t_ot/t_otfftw))

for nsize in range(10):
    size = 8**nsize
    dataX = ot.RandomGenerator.Generate(size)
    dataY = ot.RandomGenerator.Generate(size)
    data = ot.ComplexCollection([x+1j*y for (x,y) in zip(dataX, dataY)])
    t0 = time()
    res = scipy.fft.fft(data)
    t1 = time()
    t_scipy = t1 - t0
    t0 = time()
    res = ot.FFT().transform(data)
    t1 = time()
    t_ot = t1 - t0
    t0 = time()
    res = otfftw.FFTW().transform(data)
    t1 = time()
    t_otfftw = t1 - t0
    print("size=", str(size).rjust(9), "[scipy %.2e, scipy/ot %.2g, scipy/otfftw %.2g, ot/otfftw %.2g]" % (t_scipy, t_scipy/t_ot, t_scipy/t_otfftw, t_ot/t_otfftw))
```
The results:
```
size=        10 [scipy 6.65e-04, scipy/ot 6.5, scipy/otfftw 0.55, ot/otfftw 0.085]
size=       100 [scipy 4.68e-04, scipy/ot 6.3, scipy/otfftw 3, ot/otfftw 0.48]
size=      1000 [scipy 2.04e-03, scipy/ot 14, scipy/otfftw 8.2, ot/otfftw 0.6]
size=     10000 [scipy 9.28e-03, scipy/ot 17, scipy/otfftw 48, ot/otfftw 2.9]
size=    100000 [scipy 5.52e-02, scipy/ot 11, scipy/otfftw 28, ot/otfftw 2.5]
size=   1000000 [scipy 5.82e-01, scipy/ot 6.4, scipy/otfftw 22, ot/otfftw 3.4]
size=  10000000 [scipy 5.98e+00, scipy/ot 4.1, scipy/otfftw 19, ot/otfftw 4.7]
size= 100000000 [scipy 6.09e+01, scipy/ot 3.1, scipy/otfftw 15, ot/otfftw 4.7]
size=         1 [scipy 4.24e-02, scipy/ot 1.4e+03, scipy/otfftw 8.5e+02, ot/otfftw 0.61]
size=         8 [scipy 9.35e-05, scipy/ot 11, scipy/otfftw 4.6, ot/otfftw 0.42]
size=        64 [scipy 7.96e-05, scipy/ot 10, scipy/otfftw 3.6, ot/otfftw 0.35]
size=       512 [scipy 2.83e-04, scipy/ot 13, scipy/otfftw 9.1, ot/otfftw 0.72]
size=      4096 [scipy 2.12e-03, scipy/ot 16, scipy/otfftw 39, ot/otfftw 2.4]
size=     32768 [scipy 1.76e-02, scipy/ot 12, scipy/otfftw 53, ot/otfftw 4.3]
size=    262144 [scipy 1.47e-01, scipy/ot 11, scipy/otfftw 43, ot/otfftw 3.9]
size=   2097152 [scipy 1.24e+00, scipy/ot 5.1, scipy/otfftw 17, ot/otfftw 3.4]
size=  16777216 [scipy 1.02e+01, scipy/ot 4, scipy/otfftw 11, ot/otfftw 2.7]
size= 134217728 [scipy 8.40e+01, scipy/ot 3, scipy/otfftw 9.6, ot/otfftw 3.2]
```
The performance of numpy and scipy are identical (probably the same base code) and... much worst than KissFFT! I was aware of the change in the FFT implementation for numpy/scipy and was wondering if it could be a good choice for OT, and started to benchmark it two weeks ago. I am currently working on an FFT intensive project and any performance I can gain is welcomed!

**Comment by regislebrun** [comment]
And additional tests, with fftw+pthreads, fftw+omp, fftw+mpi and fftw classic (only the results of the most costly cases are shown). I modified the benchmark to get more consistent results (you can play with delta, larger values give more robust results but take more time):
```
import scipy.fft
import openturns as ot
import otfftw
from time import time

delta = 2

def checkKissFFT(data):
    t0 = time()
    reps = 0
    while time() < t0 + delta:
        reps += 1
        res = ot.FFT().transform(data)
    return (time() - t0) / reps

def checkFFTW(data):
    t0 = time()
    reps = 0
    while time() < t0 + delta:
        reps += 1
        res = otfftw.FFTW().transform(data)
    return (time() - t0) / reps

def checkScipy(data):
    t0 = time()
    reps = 0
    while time() < t0 + delta:
        reps += 1
        res = scipy.fft.fft(data)
    return (time() - t0) / reps

for size in [10, 100, 1000, 10000, 100000, 1000000, 10000000, 100000000]:
    dataX = ot.RandomGenerator.Generate(size)
    dataY = ot.RandomGenerator.Generate(size)
    data = ot.ComplexCollection([x+1j*y for (x,y) in zip(dataX, dataY)])
    t_scipy  = checkScipy(data)
    t_ot     = checkKissFFT(data)
    t_otfftw = checkFFTW(data)
    print("size=", str(size).rjust(9), "[scipy %.4e, scipy/ot %2.4g, scipy/otfftw %2.4g, ot/otfftw %2.4g]" % (t_scipy, t_scipy/t_ot, t_scipy/t_otfftw, t_ot/t_otfftw))

for nsize in range(10):
    size = 8**nsize
    dataX = ot.RandomGenerator.Generate(size)
    dataY = ot.RandomGenerator.Generate(size)
    data = ot.ComplexCollection([x+1j*y for (x,y) in zip(dataX, dataY)])
    t_scipy  = checkScipy(data)
    t_ot     = checkKissFFT(data)
    t_otfftw = checkFFTW(data)
    print("size=", str(size).rjust(9), "[scipy %.4e, scipy/ot %2.4g, scipy/otfftw %2.4g, ot/otfftw %2.4g]" % (t_scipy, t_scipy/t_ot, t_scipy/t_otfftw, t_ot/t_otfftw))
```
output:
```
# with fftw_threads
...
size=   1000000 [scipy 5.8826e-01, scipy/ot 6.396, scipy/otfftw 24.88, ot/otfftw 3.89]
size=  10000000 [scipy 5.9992e+00, scipy/ot 4.045, scipy/otfftw 19.3, ot/otfftw 4.771]
size= 100000000 [scipy 5.9665e+01, scipy/ot 3.116, scipy/otfftw 14.82, ot/otfftw 4.757]
...
# size=   2097152 [scipy 1.2349e+00, scipy/ot 4.989, scipy/otfftw 16.06, ot/otfftw 3.219]
# size=  16777216 [scipy 1.0009e+01, scipy/ot 3.962, scipy/otfftw 10.24, ot/otfftw 2.584]
# size= 134217728 [scipy 8.0356e+01, scipy/ot 2.963, scipy/otfftw 9.461, ot/otfftw 3.193]
# with fftw omp
size=   1000000 [scipy 6.0178e-01, scipy/ot 6.695, scipy/otfftw 24.53, ot/otfftw 3.664]
size=  10000000 [scipy 6.2242e+00, scipy/ot 4.124, scipy/otfftw 19.96, ot/otfftw 4.839]
size= 100000000 [scipy 6.1399e+01, scipy/ot 3.174, scipy/otfftw 14.7, ot/otfftw 4.634]
size=   2097152 [scipy 1.2715e+00, scipy/ot 5.204, scipy/otfftw 16.05, ot/otfftw 3.085]
size=  16777216 [scipy 1.0361e+01, scipy/ot 4.011, scipy/otfftw 10.33, ot/otfftw 2.576]
size= 134217728 [scipy 8.3168e+01, scipy/ot 2.977, scipy/otfftw 9.641, ot/otfftw 3.239]
# with fftw mpi
...
size=   1000000 [scipy 6.1048e-01, scipy/ot 6.601, scipy/otfftw 25.26, ot/otfftw 3.826]
size=  10000000 [scipy 6.2684e+00, scipy/ot 4.114, scipy/otfftw 20.11, ot/otfftw 4.888]
size= 100000000 [scipy 6.2138e+01, scipy/ot 3.182, scipy/otfftw 15.06, ot/otfftw 4.732]
...
size=   2097152 [scipy 1.3081e+00, scipy/ot 5.119, scipy/otfftw 16.58, ot/otfftw 3.238]
size=  16777216 [scipy 1.0454e+01, scipy/ot 3.939, scipy/otfftw 9.825, ot/otfftw 2.494]
size= 134217728 [scipy 8.3732e+01, scipy/ot 2.992, scipy/otfftw 9.671, ot/otfftw 3.232]
# with fftw classic
...
size=   1000000 [scipy 6.2166e-01, scipy/ot 6.727, scipy/otfftw 25.36, ot/otfftw 3.77]
size=  10000000 [scipy 6.2726e+00, scipy/ot 4.172, scipy/otfftw 20.13, ot/otfftw 4.825]
size= 100000000 [scipy 6.3698e+01, scipy/ot 3.238, scipy/otfftw 15.15, ot/otfftw 4.679]
...
size=   2097152 [scipy 1.3086e+00, scipy/ot 5.218, scipy/otfftw 16.8, ot/otfftw 3.219]
size=  16777216 [scipy 1.0795e+01, scipy/ot 4.209, scipy/otfftw 10.96, ot/otfftw 2.603]
size= 134217728 [scipy 8.8115e+01, scipy/ot 3.19, scipy/otfftw 10.36, ot/otfftw 3.248]
```
So there is no clear gain at using advanced versions of fftw on this benchmark. Strange.

**Pull request closed without merging**
